import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer/footer';
import NavbarClient from "@/components/navbar-links/navbar-links";
import Topbar from '@/components/top-navbar/top-navbar'
import "./globals.css";
import { WishlistProvider } from '@/context/WishlistContext';
import { SearchProvider } from '../context/SearchContext';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Eco Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SearchProvider>
        <WishlistProvider>
          <header className="sticky top-0 z-20  backdrop-blur-sm">
         <Topbar />
            <Navbar />
            <NavbarClient isAuthenticated={!!user} />
          </header>
          {children}
          <Footer />
        </WishlistProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
