import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import NavbarClient from "@/components/navbar-links/navbar-links";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Eco Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <header className="sticky top-0 z-20 bg-white">
         <Navbar/>
         <NavbarClient/>
         </header>
        {children}
         <Footer/>
      </body>
    </html>
  );
}
